name: Auto-Update

on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

concurrency:
  group: update
  cancel-in-progress: true

jobs:

  generate-jobs:
    name: Generate Jobs
    runs-on: ubuntu-latest
    outputs:
      strategy: ${{ steps.generate-jobs.outputs.strategy }}
    steps:
      - uses: actions/checkout@v3
      - id: generate-jobs
        name: Generate Jobs
        run: |
          strategy="$(
            find -name versions.json -exec dirname --zero '{}' + \
              | jq -rcsR '
                split("\u0000")
                | map(ltrimstr("./"))
                - [ "docker-master" ] # directories to skip creating branches/PRs for
                | sort
                | {
                  matrix: { dir: . },
                  "fail-fast": false,
                }
              '
          )"
          jq . <<<"$strategy" # sanity check / debugging aid
          echo "::set-output name=strategy::$strategy"

  test:
    needs: generate-jobs
    strategy: ${{ fromJson(needs.generate-jobs.outputs.strategy) }}
    name: ${{ matrix.dir }}
    runs-on: ubuntu-latest
    env:
      dir: ${{ matrix.dir }}
      branch: update/${{ matrix.dir }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Config
        run: |
          git config user.name 'Tianon (automated)'
          git config user.email 'tianon@tianon.xyz'
      - name: Rebase
        run: |
          if git fetch origin "$branch"; then
            cur="$(git rev-parse HEAD)"
            if git checkout FETCH_HEAD && git rebase "$cur"; then
              echo 'yay!'
            else
              git reset --hard "$cur"
            fi
          fi
      - name: Update
        run: |
          version_components() {
            jq -c '
              [
                .version // empty,
                (
                  to_entries[]
                  | select(.value | type == "object" and has("version"))
                  | .key + " " + .value.version
                )
              ]
            ' "$dir/versions.json"
          }
          before="$(version_components)"
          ./update.sh "$dir"
          after="$(version_components)"
          git diff || :
          message="$(jq -rn "$after - $before"' | "Update " + env.dir + if length > 0 then " to " + join(", ") else "" end')"
          before="$(git rev-parse HEAD)"
          git commit -m "$message" "$dir" || :
          after="$(git rev-parse HEAD)"
          if [ "$before" != "$after" ]; then
            git push -f origin HEAD:"$branch"
          else
            head="$(git rev-parse origin/master)"
            if [ "$after" = "$head" ]; then
              git push origin --delete "$branch" || :
            fi
          fi
